deployments:
  - path: namespace
  - barrier: true # ensure namespaces are deployed before we try to deploy anything into them
  - path: misc
  - path: entry
  - path: hat
  - path: left-arm
  - path: right-arm
  # legs are implemented via a template to showcase re-use of deployment items
  - path: template-leg
    vars:
      - values:
          leg:
            type: left
            port: 9002
    # but legs are only deployed if the target has legs enabled
    when: legs_enabled
  - path: template-leg
    vars:
      - values:
          leg:
            type: right
            port: 9004
    when: legs_enabled
