replicas:
  entry: 1
  hat: 1
  left_arm: 1
  left_leg: 1
  right_arm: 1
  right_leg: 1

legs_enabled: true

podtato:
  base_image: ghcr.io/{{ args.github_user }}
  version: {{ args.image_version or "0.2.7" }}
