apiVersion: v1
kind: ServiceAccount
metadata:
  name: podtato-head
  labels:
    app.kubernetes.io/name: podtato-head
    app.kubernetes.io/component: serviceaccount
{% if args.github_token != "" %}
    app.kubernetes.io/version: {{ podtato.version }}
    app.kubernetes.io/managed-by: kustomize
imagePullSecrets:
  - name: ghcr
{% endif %}
