---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-head-{{ leg.type }}-leg
  labels:
    app.kubernetes.io/name: podtato-head
    app.kubernetes.io/component: {{ leg.type }}-leg
spec:
  replicas: {{ replicas.get("%s_leg" % leg.type) }}
  selector:
    matchLabels:
      app.kubernetes.io/name: podtato-head
      app.kubernetes.io/component: {{ leg.type }}-leg
  template:
    metadata:
      labels:
        app.kubernetes.io/name: podtato-head
        app.kubernetes.io/component: {{ leg.type }}-leg
    spec:
      terminationGracePeriodSeconds: 5
      serviceAccountName: podtato-head
      containers:
        - name: podtato-head-{{ leg.type }}-leg
          image: {{ "%s/%s-leg:%s "% (podtato.base_image, leg.type, podtato.version) }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          resources: {}
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
