---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-head-right-arm
  labels:
    app.kubernetes.io/name: podtato-head
    app.kubernetes.io/component: right-arm
    app.kubernetes.io/version: '0.2.1'
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: podtato-head
      app.kubernetes.io/component: right-arm
  template:
    metadata:
      labels:
        app.kubernetes.io/name: podtato-head
        app.kubernetes.io/component: right-arm
    spec:
      terminationGracePeriodSeconds: 5
      serviceAccountName: podtato-head
      containers:
        - name: podtato-head-right-arm
          image: ghcr.io/podtato-head/right-arm:0.2.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources: {}
