---
apiVersion: v1
kind: Service
metadata:
  name: podtato-head-entry
  labels:
    app.kubernetes.io/name: podtato-head
    app.kubernetes.io/component: entry
  annotations:
    # local clusters will probably never get LoadBalancer services up and running
    kluctl.io/validate-ignore: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: podtato-head
    app.kubernetes.io/component: entry