{{ $componentName := "oidc-metadata" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "podtato-head.fullname" .) $componentName }}
  labels:
    {{- include "podtato-head.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ printf "%s-%s" (include "podtato-head.fullname" .) $componentName }}
stringData:
{{- if not .Values.oidc.enabled }}
    OIDC_BYPASS: 'true'
{{- else }}
    OIDC_ISSUER: {{ .Values.oidc.issuer }}
    OIDC_CLIENT_ID: {{ .Values.oidc.clientID }}
    OIDC_CLIENT_SECRET: {{ .Values.oidc.clientSecret }}
    OIDC_REDIRECT_URI: {{ .Values.oidc.redirectURI }}
    OIDC_CLIENT_SCOPES: {{ .Values.oidc.clientScopes }}
    SESSION_KEY: {{ .Values.oidc.sessionKey }}
{{- end }}
