---
apiVersion: v1
kind: Service
metadata:
  name: podtato-head-right-leg
  labels:
    app.kubernetes.io/name: podtato-head
    app.kubernetes.io/component: right-leg
    app.kubernetes.io/version: {{ podtato.version }}
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  ports:
    - port: 9004
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: podtato-head
    app.kubernetes.io/component: right-leg