---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-head-hat
  labels:
    app.kubernetes.io/name: podtato-head
    app.kubernetes.io/component: hat
    app.kubernetes.io/version: {{ podtato.version }}
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: {{ replicas.hat }}
  selector:
    matchLabels:
      app.kubernetes.io/name: podtato-head
      app.kubernetes.io/component: hat
  template:
    metadata:
      labels:
        app.kubernetes.io/name: podtato-head
        app.kubernetes.io/component: hat
    spec:
      terminationGracePeriodSeconds: 5
      serviceAccountName: podtato-head
      containers:
        - name: podtato-head-hat
          image: {{ "%s/hat:%s "% (podtato.base_image, podtato.version) }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          resources: {}
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
