name: podtato-head-test

on:
  - push
  - pull_request

permissions:
  packages: write

env:
  CONTAINER_REGISTRY: ghcr.io
  GITHUB_TOKEN: ${{ github.token }}  
  GITHUB_USER: ${{ github.repository_owner }}
  
defaults:
  run:
    shell: bash

jobs:
  push_images:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build images
        run: make push-images 

  test_services:
    needs: push_images
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test services
        run: make test-services