name: podtato-head-release

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'release-*'

permissions:
  packages: write

env:
  RELEASE_BUILD: 1
  CONTAINER_REGISTRY: ghcr.io
  GITHUB_USER: ${{ github.repository_owner }}
  # for access to ghcr.io/podtato-head instead of ghcr.io/podtato-head/podtato-head
  GITHUB_TOKEN: ${{ secrets.CR_PAT }}  
  
defaults:
  run:
    shell: bash

jobs:
  push_images:
    if: github.repository_owner == 'podtato-head'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to ghcr.io/podtato-head
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Install cosign
        uses: sigstore/cosign-installer@main
      - name: Build images
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: make push-images 

  test_services:
    if: github.repository_owner == 'podtato-head'
    needs: push_images
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test services
        run: make test-services